import asyncio, json, uuid, sys
sys.path.insert(0,'/tmp')
from playwright.async_api import async_playwright
exec(open('/tmp/t115.py').read().split("def server_rows")[0].split("from playwright.async_api import async_playwright")[1])
async def main():
    async with async_playwright() as pw:
        b=await pw.chromium.launch()
        c=await b.new_context(viewport={"width":400,"height":850},accept_downloads=True); await c.expose_function("__srv", srv)
        p=await c.new_page(); p.on("dialog", lambda d: asyncio.ensure_future(d.accept())); errs=[]; p.on("pageerror", lambda e: errs.append(str(e)))
        await p.goto("file:///tmp/b117/test.html"); await p.wait_for_timeout(400)
        L=lambda: p.evaluate("Object.values(JSON.parse(localStorage.getItem('acb-library-v1')).items).map(i=>i.name).sort()")
        print("1 big box hidden:", await p.evaluate("document.querySelector('#libCard').hidden"), "| search box visible:", await p.is_visible("#aQ"))
        await p.fill("#aQ","a36"); await p.wait_for_timeout(60); await p.click("#aRes button >> nth=0"); await p.wait_for_timeout(300)
        await p.evaluate("window.scrollTo(0,0)"); await p.screenshot(path="/tmp/p117a.png")
        box=await p.locator("#aLoad").bounding_box()
        print("2 blue box + Reset visible on first screen:", await p.is_visible("#aLoad"), "| Reset button top y:", round(box['y']))
        opts=await p.evaluate("[...document.querySelectorAll('#hdrPick option')].map(o=>o.textContent)")
        print("3 dropdown options:", opts)
        await p.select_option("#hdrPick","act:new"); await p.wait_for_timeout(300)
        print("4 New → names:", await L(), "| search focused:", await p.evaluate("document.activeElement.id"))
        await p.fill("#aQ","sr22 g6"); await p.wait_for_timeout(60); await p.click("#aRes button >> nth=0"); await p.wait_for_timeout(300)
        await p.select_option("#hdrPick","act:manage"); await p.wait_for_timeout(200)
        await p.fill("#mgName","N456CR – SR22"); await p.wait_for_timeout(100)
        await p.screenshot(path="/tmp/p117b.png"); await p.click("#mgDone"); await p.wait_for_timeout(150)
        print("5 renamed via Manage:", await L(), "| dropdown shows:", await p.evaluate("document.querySelector('#hdrPick').selectedOptions[0].textContent"))
        await p.select_option("#hdrPick","act:manage"); await p.click("#mgDup"); await p.wait_for_timeout(250)
        print("6 duplicate (Manage reopened for the copy):", await L(), "| name field:", await p.input_value("#mgName"))
        await p.click("#mgDel"); await p.wait_for_timeout(200); print("7 delete copy:", await L())
        await p.select_option("#hdrPick","act:manage")
        async with p.expect_download() as d: await p.click("#mgBak")
        print("8 backup file:", (await d.value).suggested_filename); await p.click("#mgDone")
        bon=await p.evaluate("Object.values(JSON.parse(localStorage.getItem('acb-library-v1')).items).find(i=>i.name.includes('Bonanza')).id")
        await p.select_option("#hdrPick", bon); await p.wait_for_timeout(250)
        print("9 switch back → aircraft:", await p.input_value("#aircraft"), "| blue box Reset visible:", await p.is_visible("#aLoad"))
        await p.click("#acctBtn"); await p.fill("#siEmail","james@example.com"); await p.click("#siSend"); await p.wait_for_timeout(150)
        await p.fill("#siCode","123456"); await p.click("#siVerify"); await p.wait_for_timeout(700)
        print("10 signed in, status in Step 1:", await p.inner_text("#libSaved"), "| rows on server:", len(DB["checklists"]))
        print("errors:", errs); await b.close()
asyncio.run(main())
