// @ts-nocheck  (the shared matching rules below are plain JavaScript)
// Cali Aircrew — daily emails: currency reminders + saved-search alerts (Supabase Edge Function, Deno).
// GENERATED by build.py from src/functions/reminders.tpl.ts + src/match.js — edit those, not this file.
// Deploy: Edge Functions → Deploy a new function → name "reminders" → paste this file → turn OFF "Verify JWT".
// Runs once a day from Supabase Cron (supabase/014_reminder_schedule.sql), which sends the header x-cron-key.
//
// Secrets (Edge Functions → Secrets): RESEND_API_KEY and MAIL_FROM (already added for recovery), plus
//   REMINDER_KEY  a long random value; the same value is stored in the database vault as "reminder_key".
// Optional: SITE_URL (default https://caliaircrew.com).
//
// What it sends: for each member with reminders on, one email listing every date that is
//   60 days out, 30 days out, or lapsed within the last month — aircraft "current through",
//   flight attendant recurrent, CPR / AED / first aid. "Current through" a month = valid to the end of that month.
// Each reminder is logged (reminder_log) and never sent twice.
// Saved-search alerts: for each saved search with alerts on, crew newly matching it (not in its "seen" list) are
//   emailed to the search's owner in one digest per owner, then added to "seen" so each pilot is announced once.
// POST {"dry": true} returns the plan without sending.
import { createClient } from "npm:@supabase/supabase-js@2";

function firstKey(raw: string | undefined): string {
  if (!raw) return "";
  try { const v = JSON.parse(raw); if (typeof v === "string") return v; if (Array.isArray(v)) return String(v[0] ?? ""); if (v && typeof v === "object") return String(Object.values(v)[0] ?? ""); } catch (_) { /* plain */ }
  return raw;
}
const URL_ = Deno.env.get("SUPABASE_URL")!;
const SERVICE = Deno.env.get("SERVICE_KEY") || firstKey(Deno.env.get("SUPABASE_SECRET_KEYS")) || Deno.env.get("SUPABASE_SERVICE_ROLE_KEY") || "";
const RESEND = Deno.env.get("RESEND_API_KEY") ?? "";
const FROM = Deno.env.get("MAIL_FROM") ?? "Cali Aircrew <no-reply@caliaircrew.com>";
const KEY = Deno.env.get("REMINDER_KEY") ?? "";
const SITE = (Deno.env.get("SITE_URL") ?? "https://caliaircrew.com").replace(/\/$/, "");

export type Row = { user_id: string; email: string; kind: string; ref: string; school: string; through: string };
export type Due = Row & { stage: "60" | "30" | "lapsed"; days: number };
const MONTHS = ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"];
const SCHOOLS: Record<string, string> = { flightsafety: "FlightSafety", cae: "CAE", simcom: "SIMCOM", loft: "LOFT", factory: "factory", inhouse: "in-house", independent: "independent instructor", facts: "FACTS Training", company: "company" };
const monthText = (ym: string) => { const [y, m] = ym.split("-").map(Number); return `${MONTHS[m - 1]} ${y}`; };

/** Which reminder (if any) is due today for a "current through YYYY-MM" date. */
export function stageFor(through: string, today: Date): { stage: "60" | "30" | "lapsed"; days: number } | null {
  const m = /^(\d{4})-(\d{2})$/.exec(through || ""); if (!m) return null;
  const end = Date.UTC(+m[1], +m[2], 0);                                      // last day of the month
  const t = Date.UTC(today.getUTCFullYear(), today.getUTCMonth(), today.getUTCDate());
  const days = Math.round((end - t) / 86400000);
  if (days < 0) return days >= -31 ? { stage: "lapsed", days } : null;
  if (days <= 30) return { stage: "30", days };
  if (days <= 60) return { stage: "60", days };
  return null;
}

/** Reminders due today that haven't been sent, grouped by member. */
export function plan(rows: Row[], sent: Set<string>, today: Date): Map<string, Due[]> {
  const out = new Map<string, Due[]>();
  for (const r of rows) {
    const s = stageFor(r.through, today); if (!s) continue;
    if (sent.has([r.user_id, r.kind, r.ref, r.through, s.stage].join("|"))) continue;
    const list = out.get(r.user_id) ?? []; list.push({ ...r, ...s }); out.set(r.user_id, list);
  }
  return out;
}

export function emailText(items: Due[], names: Record<string, string>): { subject: string; text: string } {
  const label = (d: Due) => d.kind === "aircraft" ? `${names[d.ref] ?? "Aircraft"} currency${d.school ? ` (${SCHOOLS[d.school] ?? d.school})` : ""}`
    : d.kind === "fa_recurrent" ? `Flight attendant recurrent training${d.school ? ` (${SCHOOLS[d.school] ?? d.school})` : ""}` : "CPR / AED / first aid";
  const when = (d: Due) => d.stage === "lapsed" ? `lapsed at the end of ${monthText(d.through)}` : `current through ${monthText(d.through)} (${d.days} day${d.days === 1 ? "" : "s"} left)`;
  const lapsed = items.some(d => d.stage === "lapsed");
  const subject = lapsed ? "Cali Aircrew: currency lapsed" : items.length === 1 ? `Cali Aircrew: ${label(items[0])} coming due` : "Cali Aircrew: currency coming due";
  const lines = items.sort((a, b) => a.days - b.days).map(d => `• ${label(d)}: ${when(d)}`);
  const text = `Hello,\n\nA reminder from Cali Aircrew about dates on your crew profile:\n\n${lines.join("\n")}\n\n` +
    `Once you've completed training, update the date so your profile shows you as current:\n${SITE}/crew/#/me\n\n` +
    (lapsed ? "Until then, your profile shows that currency as expired.\n\n" : "") +
    `You get these emails because these dates are on your Cali Aircrew profile. To turn them off: ${SITE}/crew/#/account\n\nCali Aircrew`;
  return { subject, text };
}

async function sendMail(to: string, subject: string, text: string) {
  if (!RESEND) throw new Error("RESEND_API_KEY missing");
  const r = await fetch("https://api.resend.com/emails", { method: "POST", headers: { Authorization: `Bearer ${RESEND}`, "Content-Type": "application/json" }, body: JSON.stringify({ from: FROM, to: [to], subject, text }) });
  if (!r.ok) throw new Error("Email service error " + r.status);
}

/* ---------------- shared Find crew matching rules (src/match.js) ---------------- */
/* Cali Aircrew — Find crew matching rules. ONE copy, inserted by build.py into the crew pages (src/crew.js) and the
   daily email job (supabase/functions/reminders), so saved-search alerts always agree with what Find crew shows.
   env = { info: seq -> {engine, twin, heli} | undefined,  ll: airportCode -> [lat, lon] | null }               */
const RATE_LOW = {u500:0, "500":500, "750":750, "1000":1000, "1250":1250, "1500":1500, "2000":2000, "2500":2500, "3000":3000};
const monthNow = () => { const n = new Date(); return n.getFullYear() + "-" + String(n.getMonth() + 1).padStart(2, "0"); };
const ROLEF = {
  flight_attendant:[["fa_cpr","CPR / AED current", d => !!d.cpr_until && d.cpr_until >= monthNow()], ["fa_rec","FA recurrent current", d => !!d.fa_recurrent && d.fa_recurrent >= monthNow()],
    ["fa_intl","International trips", d => (d.fa_skills || []).includes("intl")], ["fa_cul","Culinary / chef training", d => (d.fa_skills || []).includes("culinary")], ["fa_food","Food safety certificate", d => !!d.food_safety]],
  mechanic:[["mx_ap","A&P", d => (d.mx_certs || []).includes("ap") || (d.ratings || []).includes("ap")], ["mx_ia","IA", d => (d.mx_certs || []).includes("ia") || (d.ratings || []).includes("ia")],
    ["mx_av","Avionics", d => (d.mx_spec || []).includes("avionics") || (d.mx_certs || []).includes("fcc")], ["mx_aog","AOG road trips", d => !!d.mx_aog], ["mx_135","Part 135 maintenance", d => (d.mx_exp || []).includes("p135")]],
  helicopter_pilot:[["h_nvg","NVG", d => (d.heli_ops || []).includes("nvg")], ["h_ll","Long line / external load", d => (d.heli_ops || []).includes("longline")], ["h_ems","EMS / air medical", d => (d.heli_ops || []).includes("ems")],
    ["h_fire","Firefighting", d => (d.heli_ops || []).includes("fire")], ["h_tour","Tours", d => (d.heli_ops || []).includes("tours")], ["h_r44","R44 SFAR 73", d => (d.sfar73 || []).includes("r44")], ["h_r22","R22 SFAR 73", d => (d.sfar73 || []).includes("r22")]]
};
/* Hours by engine type from per-aircraft hours. Turbine = jet + turboprop + turbine helicopter. */
function hoursByTypeWith(info, aircraft){
  const t = {jet:0, turboprop:0, piston:0, multi:0, heliT:0, heliP:0};
  for (const a of aircraft || []) { const i = info(a.acft_seq), h = +a.hours || 0; if (!i || !h) continue;
    if (i.heli) { if (i.engine === "piston") t.heliP += h; else t.heliT += h; }
    else if (i.engine === "jet") t.jet += h; else if (i.engine === "turboprop") t.turboprop += h; else t.piston += h;
    if (i.twin && !i.heli) t.multi += h; }
  t.turbine = t.jet + t.turboprop + t.heliT; t.heli = t.heliT + t.heliP; return t;
}
const acRate = (d, seq) => (d.ac_rate && seq != null && d.ac_rate[seq]) || d.rate || "";
const distNm = (a, b) => { const R = 3440.065, r = x => x * Math.PI / 180, dLa = r(b[0] - a[0]), dLo = r(b[1] - a[1]);
  const h = Math.sin(dLa / 2) ** 2 + Math.cos(r(a[0])) * Math.cos(r(b[0])) * Math.sin(dLo / 2) ** 2; return 2 * R * Math.asin(Math.sqrt(h)); };
/* FAA type ratings a pilot holds: from aircraft marked "type rated", using the rating they picked when an aircraft
   spans two FAA ratings (details.tr_des), plus the single-pilot "S" rating when ticked (details.tr_sp).
   A single-pilot rating also counts for the base rating (CE-525S holders match a CE-525 search). */
function typeRatings(p, ac, env){
  const d = p.details || {}, out = new Set();
  for (const a of ac || []) { if (!a.type_rated) continue; const opts = env.tr ? env.tr(a.acft_seq) : null; if (!opts || !opts.length) continue;
    const pick = opts.find(o => o[0] === (d.tr_des || {})[a.acft_seq]) || opts[0]; out.add(pick[0]); if (pick[1] && (d.tr_sp || {})[a.acft_seq]) out.add(pick[1]); }
  return out;
}
function matchProfile(F, p, ac, env){
  const d = p.details || {}, seq = F.seq != null && F.seq !== "" ? +F.seq : null;
  if (F.type && !(p.crew_types || []).includes(F.type)) return false;
  if (seq != null && !ac.some(a => a.acft_seq === seq)) return false;
  if (F.region && d.region !== F.region) return false;
  if (F.cert && d.cert !== F.cert) return false;
  if (F.avail === "now" && d.status !== "now") return false;
  if (F.avail === "soon" && d.status !== "now" && d.status !== "notice") return false;
  if (F.contract && !(d.looking || []).includes("contract")) return false;
  if (F.p135 && !ac.some(a => a.part135 && (seq == null || a.acft_seq === seq))) return false;
  const rr = acRate(d, seq);
  if (F.rate && rr && rr !== "ask" && RATE_LOW[rr] >= +F.rate) return false;   // "Ask me" and not-stated stay in
  if (F.minTT && (+p.total_time || 0) < +F.minTT) return false;
  if (F.minPIC && (+d.hrs_pic || 0) < +F.minPIC) return false;
  if (F.minTurb && hoursByTypeWith(env.info, ac).turbine < +F.minTurb) return false;
  if (F.minType && seq != null && (+((ac.find(a => a.acft_seq === seq) || {}).hours) || 0) < +F.minType) return false;
  if (F.trn && !(d.training || []).includes(F.trn)) return false;
  if (F.tr && !typeRatings(p, ac, env).has(F.tr)) return false;
  if (F.near) { const c = env.ll(F.near), h = env.ll(d.airport); if (c && (!h || distNm(c, h) > +(F.nm || 100))) return false; }
  for (const k of (F.x || [])) { const f = (ROLEF[F.type] || []).find(r => r[0] === k); if (f && !f[2](d)) return false; }
  if (F.eng && F.type === "mechanic" && !(d.mx_engines || []).includes(F.eng)) return false;
  return true;
}
/* Name shown publicly: initials only when the member chose that ("Dana Pilot" -> "D. P."). */
const publicName = p => (p.details || {}).initials ? String(p.display_name || "").split(/\s+/).filter(Boolean).map(w => w[0].toUpperCase() + ".").join(" ") : (p.display_name || "");


/* ---------------- saved-search alerts ---------------- */
const REGION_LABEL: Record<string, string> = { socal: "Southern California", norcal: "Northern California", pnw: "Pacific Northwest", southwest: "Southwest", mountain: "Mountain",
  texas: "Texas", midwest: "Midwest", southeast: "Southeast", florida: "Florida", northeast: "Northeast", hawaii: "Hawaii", alaska: "Alaska", intl: "Outside the US" };
async function searchAlerts(admin, dry: boolean) {
  const out = { searches: 0, owners: 0, newMatches: 0, emails: 0, failed: 0, preview: [] as unknown[] };
  const { data: owners } = await admin.rpc("search_alert_owners"); if (!owners || !owners.length) return out;
  const emailOf = new Map(owners.map((o: Record<string, unknown>) => [o.id, o.email]));
  const { data: searches } = await admin.from("saved_searches").select("id,user_id,name,filters,seen").eq("alerts", true);
  const list = (searches ?? []).filter((x: Record<string, unknown>) => emailOf.has(x.id)); out.searches = list.length; if (!list.length) return out;
  const [{ data: profs }, { data: mods }] = await Promise.all([admin.from("crew_profiles").select("*").eq("published", true), admin.from("moderation").select("user_id,approved,hidden")]);
  const ok = new Set((mods ?? []).filter((m: Record<string, unknown>) => m.approved && !m.hidden).map((m: Record<string, unknown>) => m.user_id));
  const listed = (profs ?? []).filter((p: Record<string, unknown>) => ok.has(p.user_id));
  const { data: acRows } = listed.length ? await admin.from("crew_aircraft").select("*").in("user_id", listed.map((p: Record<string, unknown>) => p.user_id)) : { data: [] };
  const acBy = new Map(); (acRows ?? []).forEach((a: Record<string, unknown>) => { const l = acBy.get(a.user_id) ?? []; l.push(a); acBy.set(a.user_id, l); });
  let info: Record<string, unknown[]> = {}; try { const r = await fetch(`${SITE}/crew/aircraft-info.json`); if (r.ok) info = await r.json(); } catch (_) { /* optional */ }
  let trMap: Record<string, string[][]> = {}; try { const r = await fetch(`${SITE}/crew/type-ratings.json`); if (r.ok) trMap = await r.json(); } catch (_) { /* optional */ }
  let airports: Record<string, string> | null = null;
  if (list.some((x: Record<string, Record<string, unknown>>) => x.filters && x.filters.near)) { try { const r = await fetch(`${SITE}/crew/airports.json`); if (r.ok) airports = await r.json(); } catch (_) { /* optional */ } }
  const rec = (c: string) => { const k = String(c || "").toUpperCase(); return airports && k ? (airports[k] || airports["K" + k] || (k.length === 4 && k[0] === "K" ? airports[k.slice(1)] : "") || "") : ""; };
  const env = { info: (sq: number) => { const i = info[String(sq)]; return i ? { engine: i[1], twin: !!i[2], heli: !!i[3] } : undefined; },
                tr: (sq: number) => trMap[String(sq)] || null,
                ll: (c: string) => { const p = rec(c).split("|"); return p.length === 3 ? [+p[1], +p[2]] : null; } };
  const byOwner = new Map();
  for (const s of list) {
    const seen = new Set(s.seen ?? []);
    const hits = listed.filter((p: Record<string, unknown>) => p.user_id !== s.user_id && matchProfile(s.filters || {}, p, acBy.get(p.user_id) ?? [], env));
    const fresh = hits.filter((p: Record<string, unknown>) => !seen.has(p.user_id)); if (!fresh.length) continue;
    out.newMatches += fresh.length;
    const e = byOwner.get(s.user_id) ?? { email: emailOf.get(s.id), items: [] }; e.items.push({ s, fresh }); byOwner.set(s.user_id, e);
  }
  out.owners = byOwner.size;
  for (const [, e] of byOwner) {
    const n = e.items.reduce((t: number, x: { fresh: unknown[] }) => t + x.fresh.length, 0);
    const subject = `Cali Aircrew: ${n === 1 ? "1 new crew member matches" : n + " new crew match"} your saved search${e.items.length === 1 ? ` "${e.items[0].s.name}"` : "es"}`;
    const blocks = e.items.map(({ s, fresh }: { s: Record<string, unknown>, fresh: Record<string, unknown>[] }) => {
      const sq = (s.filters as Record<string, unknown>)?.seq; const q = sq != null && sq !== "" ? `?a=${sq}` : "";
      return `${s.name}:\n` + fresh.slice(0, 15).map(p => { const d = (p.details || {}) as Record<string, unknown>; const base = [d.airport, REGION_LABEL[String(d.region || "")] || ""].filter(Boolean).join(" · ");
        return `• ${publicName(p)}${base ? " — " + base : ""}\n  ${SITE}/crew/#/p/${p.user_id}${q}`; }).join("\n") + (fresh.length > 15 ? `\n  …and ${fresh.length - 15} more` : ""); });
    const text = `Hello,\n\nNew crew on Cali Aircrew match your saved searches:\n\n${blocks.join("\n\n")}\n\n` +
      `See all your saved searches: ${SITE}/crew/#/saved\nTo stop these emails, turn off alerts on a search there.\n\nCali Aircrew`;
    if (dry) { if (out.preview.length < 3) out.preview.push({ subject, searches: e.items.map((x: { s: Record<string, unknown>, fresh: unknown[] }) => [x.s.name, x.fresh.length]) }); continue; }
    try {
      await sendMail(e.email, subject, text); out.emails++;
      for (const { s, fresh } of e.items) {
        const seen = Array.from(new Set([...(s.seen ?? []), ...fresh.map((p: Record<string, unknown>) => p.user_id)])).slice(-1000);
        await admin.from("saved_searches").update({ seen, last_alert: new Date().toISOString() }).eq("id", s.id);
      }
    } catch (_) { out.failed++; }
  }
  return out;
}

Deno.serve(async (req) => {
  const reply = (b: unknown, s = 200) => new Response(JSON.stringify(b), { status: s, headers: { "Content-Type": "application/json" } });
  if (req.method !== "POST") return reply({ ok: false, message: "POST only" }, 405);
  if (!KEY || req.headers.get("x-cron-key") !== KEY) return reply({ ok: false, message: "Not authorized" }, 401);
  if (!SERVICE) return reply({ ok: false, message: "Server key missing" }, 500);
  let body: { dry?: boolean } = {}; try { body = await req.json(); } catch (_) { /* empty body is fine */ }
  const admin = createClient(URL_, SERVICE, { auth: { persistSession: false, autoRefreshToken: false } });
  const { data: rows, error } = await admin.rpc("reminder_candidates"); if (error) return reply({ ok: false, message: error.message }, 500);
  const ids = [...new Set((rows as Row[]).map(r => r.user_id))];
  const sent = new Set<string>();
  for (let i = 0; i < ids.length; i += 200) {
    const { data: logs } = await admin.from("reminder_log").select("user_id,kind,ref,through,stage").in("user_id", ids.slice(i, i + 200));
    (logs ?? []).forEach((l: Record<string, string>) => sent.add([l.user_id, l.kind, l.ref, l.through, l.stage].join("|")));
  }
  const due = plan(rows as Row[], sent, new Date());
  let names: Record<string, string> = {};
  try { const r = await fetch(`${SITE}/crew/aircraft-names.json`); if (r.ok) names = await r.json(); } catch (_) { /* names are optional */ }
  const result = { ok: true, dry: !!body.dry, members: due.size, reminders: 0, emails: 0, failed: 0, preview: [] as unknown[] };
  for (const [uid, items] of due) {
    const { subject, text } = emailText(items, names);
    result.reminders += items.length;
    if (body.dry) { if (result.preview.length < 5) result.preview.push({ subject, items: items.map(d => [d.kind, d.ref, d.through, d.stage]) }); continue; }
    try {
      await sendMail(items[0].email, subject, text);
      await admin.from("reminder_log").insert(items.map(d => ({ user_id: uid, kind: d.kind, ref: d.ref, through: d.through, stage: d.stage })));
      result.emails++;
    } catch (_) { result.failed++; }
  }
  let alerts = {}; try { alerts = await searchAlerts(admin, !!body.dry); } catch (e) { alerts = { error: (e as Error).message }; }
  return reply({ ...result, alerts });
});
